const ReduxValues = {
  RestApiActions: {},
  GlobalActions: {
    SET_IS_LOADING: "SET_IS_LOADING",
    SET_SNACKBAR: "SET_SNACKBAR",
    SET_FILTER_SETTINGS: "SET_FILTER_SETTINGS",
    SET_PRODUCTS_FETCHED: "SET_PRODUCTS_FETCHED",
    SET_CATEGORIES: "SET_CATEGORIES",
    SET_PRODUCT_SELECTED: "SET_PRODUCT_SELECTED",
  },
};
export default ReduxValues;
